#include <stdio.h>

#define I_THINK_I_SHOULD_NEVER_SEE int main(void){
#define A_POEM_LOVELY_AS_A_TREE printf("C program");
#define A_THREE_WHOS_hUNGRY_MOUTH_IS_PRESSED return 0;
#define AGAINS_THE_SWEET_EARTHS_FLOWING_BREAST }

I_THINK_I_SHOULD_NEVER_SEE
A_POEM_LOVELY_AS_A_TREE
A_THREE_WHOS_hUNGRY_MOUTH_IS_PRESSED
AGAINS_THE_SWEET_EARTHS_FLOWING_BREAST